BookShop/BookShop/BookShop/BookShop/Controllers/AuthController.cs
using MusicEvents.Common;
using MusicEvents.Data;
using MusicEvents.Models;
using MusicEvents.Repositories;
using MusicEvents.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace MusicEvents.Controllers;

[Route("[controller]/[action]")]
public class AuthController : Controller
{
    private readonly UserRepository _userRepository;
    private readonly Hasher _hasher;

    public AuthController(UserRepository userRepository, Hasher hasher)
    {
        _userRepository = userRepository;
        _hasher = hasher;
    }
    
    [HttpGet]
    public IActionResult Register()
    {
        if (CurrentUser.CurrentUserId != null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        var model = new RegisterViewModel();
        
        return View(model);
    }

    [HttpPost]
    public IActionResult Register(RegisterViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (_userRepository.GetByEmail(model.Email) != null)
        {
            ModelState.AddModelError(nameof(model.Email), "User with that email already exists.");
            return View(model);
        }

        var user = new User
        {
            FirstName = model.FirstName,
            LastName = model.LastName,
            Email = model.Email,
            PasswordHash = _hasher.GetHash(model.Password)
        };

        _userRepository.Create(user);

        return RedirectToAction("LogIn");
    }

    [HttpGet]
    public IActionResult LogIn()
    {
        if (CurrentUser.CurrentUserId != null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        var model = new LogInViewModel();

        return View(model);
    }

    [HttpPost]
    public IActionResult LogIn(LogInViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
        
        var user = _userRepository.GetByEmail(model.Email);

        if (user == null)
        {
            ModelState.AddModelError(nameof(model.Password), "Invalid credentials.");
            return View(model);
        }

        if (user.PasswordHash != _hasher.GetHash(model.Password))
        {
            ModelState.AddModelError(nameof(model.Password), "Invalid credentials.");
            return View(model);
        }

        CurrentUser.CurrentUserId = user.Id;

        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult LogOut()
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        CurrentUser.CurrentUserId = null;

        return RedirectToAction("Index", "Home");
    }
}

BookShop/BookShop/BookShop/BookShop/Controllers/EventController.cs
using System.Text;
using MusicEvents.Common;
using MusicEvents.Data;
using MusicEvents.Models;
using MusicEvents.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace MusicEvents.Controllers;

[Route("[controller]/[action]")]
public class EventController : Controller
{
    private readonly UserRepository _userRepository;
    private readonly EventRepository _eventRepository;

    public EventController(UserRepository userRepository, EventRepository eventRepository)
    {
        _userRepository = userRepository;
        _eventRepository = eventRepository;
    }
    
    [HttpGet]
    public IActionResult CreateEvent()
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        var model = new CreateEventViewModel();
        return View(model);
    }

    [HttpPost]
    public IActionResult CreateEvent(CreateEventViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (model.Image != null &&
            model.Image.ContentType != "image/png" &&
            model.Image.ContentType != "image/jpeg")
        {
            ModelState.AddModelError(nameof(model.Image), "File must be in .png or in .jpeg format.");
            return View(model);
        }
        
        if (CurrentUser.CurrentUserId == null)
        {
            return NotFound();
        }

        var user = _userRepository.GetById((Guid)CurrentUser.CurrentUserId);

        if (user == null)
        {
            return NotFound();
        }

        var imageBase64 = string.Empty;
        
        if (model.Image != null)
        {
            using var memoryStream = new MemoryStream();
            model.Image.CopyTo(memoryStream);
            var bytes = memoryStream.ToArray();
            imageBase64 = Convert.ToBase64String(bytes);
        }
        
        var _event = new Music
        {
            Name = model.Name,
            Content = model.Content,
            IsPublic = model.IsPublic,
            User = user,
            ImageBase64 = imageBase64
        };

        _eventRepository.Create(_event);
        
        return RedirectToAction("MyEvents");
    }

    [HttpGet]
    public IActionResult MyEvents()
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return RedirectToAction("Index", "Home");
        }
        
        var events = _eventRepository.GetAllFromUser((Guid)CurrentUser.CurrentUserId);

        var model = events.Select(selector: Music => new MyEventViewModel
        {
            Id = Music.Id,
            Name = Music.Name,
            IsPublic = Music.IsPublic,
            Content = Music.Content,
            ImageBase64 = Music.ImageBase64
                // .Split(' ', StringSplitOptions.RemoveEmptyEntries)
                // .Aggregate(new StringBuilder(), (sb, word) =>
                // {
                //     if (sb.Length + word.Length > 100)
                //     {
                //         sb.AppendLine();
                //     }
                //
                //     sb.Append(word).Append(' ');
                //     return sb;
                // })
                // .ToString()
                // .Trim()
        }).ToList();

        return View(model);
    }

    [HttpGet]
    public IActionResult PublicEvents()
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return RedirectToAction("Index", "Home");
        }

        var _events = _eventRepository.GetPublic();

        var model = _events.Select(b => new PublicEventViewModel
        {
            Name = b.Name,
            Content = b.Content,
            Author = $"{b.User.FirstName} {b.User.LastName}",
            ImageBase64 = b.ImageBase64
        }).ToList();

        return View(model);
    }

    [HttpGet("{id:guid}")]
    public IActionResult UpdateEvent([FromRoute] Guid id)
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return RedirectToAction("Index", "Home");
        }

        var _event = _eventRepository.GetById(id);

        if (_event == null)
        {
            return NotFound();
        }

        var model = new UpdateEventViewModel
        {
            Name = _event.Name,
            Content = _event.Content,
            IsPublic = _event.IsPublic
        };

        return View(model);
    }

    [HttpPost("{id:guid}")]
    public IActionResult UpdateEvent([FromRoute] Guid id, UpdateEventViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        if (CurrentUser.CurrentUserId == null)
        {
            return NotFound();
        }

        var _event = _eventRepository.GetById(id);

        if (_event == null)
        {
            return NotFound();
        }
        
        _event.Name = model.Name;
        _event.Content = model.Content;
        _event.IsPublic = model.IsPublic;

        _eventRepository.Update(_event);

        return RedirectToAction("MyEvents");
    }

    [HttpPost("{id:guid}")]
    public IActionResult DeleteEvent([FromRoute] Guid id)
    {
        if (CurrentUser.CurrentUserId == null)
        {
            return NotFound();
        }

        var _event = _eventRepository.GetById(id);

        if (_event == null)
        {
            return NotFound();
        }
        
        _eventRepository.Delete(_event);

        return RedirectToAction("MyEvents");
    }
}

BookShop/BookShop/BookShop/BookShop/Views/Shared/_Layout.cshtml
@using MusicEvents.Common
@using MusicEvents.Repositories
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MusicEvents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MusicEvents.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicEvents</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (CurrentUser.CurrentUserId == null)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LogIn">Log In</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="CreateEvent">Create Event</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="MyEvents">My Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="PublicEvents">Public Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="LogOut">Log Out</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - MusicEvents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>